### PR TITLE
juniverse.opam should include the dependencies, not the sources

### PR DESCRIPTION
**Pull request by avsm**
This repository contains a series of packages from the JS monorepo.
To use duniverse, you need to encode the _dependencies_ of those
packages, so that the duniverse tool can vendor the code required
to build them all.

If you run `duniverse init` after this PR, you'll notice fewer
errors, but not zero errors. Some of the dependencies (such as
notty or cryptokit) have not been ported to dune yet, so you will
need to do so and add a fork to
https://github.com/dune-universe/opam-overlays.

There is also a clash between the use of omp and ppxlib, which
@jeremiedimino probably has a plan for.

### CODE REVIEW

**Comment by snowleopard** [comment]
Many thanks @avsm! All sounds good to me.

I'll try to compute the dependencies by parsing `opam` files, taking the union of their dependencies, and then removing the initial set. (It seems to me that this would be a useful functionality in general, so I'm happy to contribute this code to duniverse of elsewhere if you think that would be helpful.)

Could you add a sign-off commit bit so I could merge?

**Comment by avsm** [comment]
@jeremiedimino the bug was actually not a ppx clash. `duniverse` currently scans only the toplevel dir for *.opam. We need to scan subdirs (except for duniverse/) to find all the root packages present in the repo. This will let duniverse locate libraries like stdio/base within this monorepo and not duplicate them.  The duplication was causing the bug I saw.

With the latest push

```
duniverse init
duniverse pull
rm -rf duniverse/base* duniverse/stdio* duniverse/sexplib*
dune build
```

manages to build over 50000 jobs. Not bad :-)

**Comment by avsm** [comment]
@snowleopard: re the "missing libraries", if dune could get a feature to print those in an easily parseable way, then duniverse (and other tools) can use that. It would be good if that logic stayed in dune.

rebased and pushed with a DCO.  I'll fix that duniverse issue with opam scanning, and then we can activate ocaml-ci on this repository.

**Comment by snowleopard** [comment]
@avsm Sounds good, thank you!

**Pull request merged**
